# -*- encoding: utf-8 -*-

=begin
#OnChain Crypto Currency API

#Swagger definition for this API is available at https://io/docs/swagger.json

The version of the OpenAPI document: 1.0
Contact: support@io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-beta

=end

$:.push File.expand_path("../lib", __FILE__)
require "onchain-api/version"

Gem::Specification.new do |s|
  s.name        = "onchain-api"
  s.version     = OnchainApi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@io"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "OnChain Crypto Currency API Ruby Gem"
  s.description = "Swagger definition for this API is available at https://io/docs/swagger.json"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
