=begin
#OnChain Crypto Currency API

#Swagger defrinition for this API is available at https://io/docs/swagger.json

OpenAPI spec version: 1.0
Contact: support@io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module OnchainApi
  class CoinType
    
    BITCOIN = 'BITCOIN'.freeze
    ETHEREUM = 'ETHEREUM'.freeze
    TESTNET3 = 'TESTNET3'.freeze
    BITCOIN_CASH = 'BITCOIN_CASH'.freeze
    BITCOIN_GOLD = 'BITCOIN_GOLD'.freeze
    LITECOIN = 'LITECOIN'.freeze
    DASH = 'DASH'.freeze
    DOGE = 'DOGE'.freeze
    BITCOIN_PRIVATE = 'BITCOIN_PRIVATE'.freeze
    ZCASH = 'ZCASH'.freeze
    ZCASH_TESTNET = 'ZCASH_TESTNET'.freeze
    ZCLASSIC = 'ZCLASSIC'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CoinType.constants.select { |c| CoinType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CoinType" if constantValues.empty?
      value
    end
  end
end
