=begin
#OnChain Crypto Currency API

#Swagger definition for this API is available at https://io/docs/swagger.json

OpenAPI spec version: 1.0
Contact: support@io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module OnchainApi
  VERSION = '1.1.6'
end
