=begin
#OnChain Crypto Currency API

#Swagger definition for this API is available at https://io/docs/swagger.json

OpenAPI spec version: 1.0
Contact: support@io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OnchainApi::CoinType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CoinType' do
  before do
    # run before each test
    @instance = OnchainApi::CoinType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CoinType' do
    it 'should create an instance of CoinType' do
      expect(@instance).to be_instance_of(OnchainApi::CoinType)
    end
  end
end
