=begin
#OnChain Crypto Currency API

#Swagger definition for this API is available at https://io/docs/swagger.json

The version of the OpenAPI document: 1.0
Contact: support@io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-beta

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OnchainApi::PaymentRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentRequest' do
  before do
    # run before each test
    @instance = OnchainApi::PaymentRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentRequest' do
    it 'should create an instance of PaymentRequest' do
      expect(@instance).to be_instance_of(OnchainApi::PaymentRequest)
    end
  end
  describe 'test attribute "coin_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "recipients"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "miners_fee"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
