=begin
#OnChain Crypto Currency API

#We need to add a proper description.

OpenAPI spec version: 1.0
Contact: support@onchain.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OnchainApi::AddressApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddressApi' do
  before do
    # run before each test
    @instance = OnchainApi::AddressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressApi' do
    it 'should create an instance of AddressApi' do
      expect(@instance).to be_instance_of(OnchainApi::AddressApi)
    end
  end

  # unit tests for address_get_balance
  # Get Balance
  # Returns the satoshi balance, usd balance and user viewable balance for an address. For ERC20 tokens you need to pass in the contract ID and the number of decimal places.
  # @param coin_type 
  # @param address The public address to lookup
  # @param [Hash] opts the optional parameters
  # @return [OnchainBalanceReply]
  describe 'address_get_balance test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for address_get_balances
  # Get Balances
  # Returns the satoshi balance, usd balance and user viewable balance for a set of addresses.
  # @param coin_type 
  # @param addresses 
  # @param [Hash] opts the optional parameters
  # @return [OnchainBalancesReply]
  describe 'address_get_balances test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for address_get_history
  # Get History
  # Returns the transaction history for an address or addresses.
  # @param coin_type 
  # @param addresses 
  # @param [Hash] opts the optional parameters
  # @return [OnchainHistoryReply]
  describe 'address_get_history test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for address_get_network_address
  # @param coin_type 
  # @param public_key 
  # @param [Hash] opts the optional parameters
  # @return [OnchainAddressReply]
  describe 'address_get_network_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
