=begin
#OnChain Crypto Currency API

#Swagger defrinition for this API is available at https://io/docs/swagger.json

OpenAPI spec version: 1.0
Contact: support@io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for OnchainApi::ERC20TransactionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ERC20TransactionApi' do
  before do
    # run before each test
    @instance = OnchainApi::ERC20TransactionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ERC20TransactionApi' do
    it 'should create an instance of ERC20TransactionApi' do
      expect(@instance).to be_instance_of(OnchainApi::ERC20TransactionApi)
    end
  end

  # unit tests for create_transaction
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EthereumTransactionReply]
  describe 'create_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sign_and_send
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [TransactionSendReply]
  describe 'sign_and_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
