=begin
#OnChain Crypto Currency API

#We need to add a proper description.

OpenAPI spec version: 1.0
Contact: support@onchain.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Onchain::TransactionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionApi' do
  before do
    # run before each test
    @instance = Onchain::TransactionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionApi' do
    it 'should create an instance of TransactionApi' do
      expect(@instance).to be_instance_of(Onchain::TransactionApi)
    end
  end

  # unit tests for transaction_create_transaction
  # @param coin_type 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [OnchainTransactionReply]
  describe 'transaction_create_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_send_raw
  # @param coin_type 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [OnchainTransactionSendReply]
  describe 'transaction_send_raw test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_sign_and_send
  # @param coin_type 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [OnchainTransactionSendReply]
  describe 'transaction_sign_and_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
