=begin
#OnChain Crypto Currency API

#Swagger definition for this API is available at https://io/docs/swagger.json

The version of the OpenAPI document: 1.0
Contact: support@io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-beta

=end

require 'spec_helper'

describe OnchainApi::Configuration do
  let(:config) { OnchainApi::Configuration.default }

  before(:each) do
    # uncomment below to setup host and base_path
    # require 'URI'
    # uri = URI.parse("http://onchain.io")
    # OnchainApi.configure do |c|
    #   c.host = uri.host
    #   c.base_path = uri.path
    # end
  end

  describe '#base_url' do
    it 'should have the default value' do
      # uncomment below to test default value of the base path
      # expect(config.base_url).to eq("http://onchain.io")
    end

    it 'should remove trailing slashes' do
      [nil, '', '/', '//'].each do |base_path|
        config.base_path = base_path
        # uncomment below to test trailing slashes
        # expect(config.base_url).to eq("http://onchain.io")
      end
    end
  end
end
