/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressReply {
    #[serde(rename = "network_address", skip_serializing_if = "Option::is_none")]
    pub network_address: Option<String>,
}

impl AddressReply {
    pub fn new() -> AddressReply {
        AddressReply {
            network_address: None,
        }
    }
}


