/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceAddressReply {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "usd_balance", skip_serializing_if = "Option::is_none")]
    pub usd_balance: Option<f32>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    #[serde(rename = "unconfirmed_balance", skip_serializing_if = "Option::is_none")]
    pub unconfirmed_balance: Option<String>,
    #[serde(rename = "human_balance", skip_serializing_if = "Option::is_none")]
    pub human_balance: Option<f64>,
    #[serde(rename = "human_unconfirmed_balance", skip_serializing_if = "Option::is_none")]
    pub human_unconfirmed_balance: Option<f64>,
}

impl BalanceAddressReply {
    pub fn new() -> BalanceAddressReply {
        BalanceAddressReply {
            address: None,
            usd_balance: None,
            balance: None,
            unconfirmed_balance: None,
            human_balance: None,
            human_unconfirmed_balance: None,
        }
    }
}


