/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalancesReply {
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<crate::models::BalanceAddressReply>>,
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<crate::models::BalanceReply>,
}

impl BalancesReply {
    pub fn new() -> BalancesReply {
        BalancesReply {
            addresses: None,
            totals: None,
        }
    }
}


