/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoinType {
    #[serde(rename = "BITCOIN")]
    BITCOIN,
    #[serde(rename = "ETHEREUM")]
    ETHEREUM,
    #[serde(rename = "TESTNET3")]
    TESTNET3,
    #[serde(rename = "BITCOIN_CASH")]
    BITCOINCASH,
    #[serde(rename = "BITCOIN_GOLD")]
    BITCOINGOLD,
    #[serde(rename = "LITECOIN")]
    LITECOIN,
    #[serde(rename = "DASH")]
    DASH,
    #[serde(rename = "DOGE")]
    DOGE,
    #[serde(rename = "BITCOIN_PRIVATE")]
    BITCOINPRIVATE,
    #[serde(rename = "ZCASH")]
    ZCASH,
    #[serde(rename = "ZCASH_TESTNET")]
    ZCASHTESTNET,
    #[serde(rename = "ZCLASSIC")]
    ZCLASSIC,

}




