/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EthereumTransactionReply {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "to_sign", skip_serializing_if = "Option::is_none")]
    pub to_sign: Option<String>,
}

impl EthereumTransactionReply {
    pub fn new() -> EthereumTransactionReply {
        EthereumTransactionReply {
            tx: None,
            to_sign: None,
        }
    }
}


