/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryReplyTx {
    #[serde(rename = "confirmations", skip_serializing_if = "Option::is_none")]
    pub confirmations: Option<i32>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
    #[serde(rename = "is_deposit", skip_serializing_if = "Option::is_none")]
    pub is_deposit: Option<bool>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    #[serde(rename = "human_amount", skip_serializing_if = "Option::is_none")]
    pub human_amount: Option<f32>,
}

impl HistoryReplyTx {
    pub fn new() -> HistoryReplyTx {
        HistoryReplyTx {
            confirmations: None,
            time: None,
            is_deposit: None,
            address: None,
            amount: None,
            human_amount: None,
        }
    }
}


