/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSendRequest {
    #[serde(rename = "coin_type", skip_serializing_if = "Option::is_none")]
    pub coin_type: Option<crate::models::CoinType>,
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "signatures", skip_serializing_if = "Option::is_none")]
    pub signatures: Option<Vec<crate::models::HashToSign>>,
}

impl TransactionSendRequest {
    pub fn new() -> TransactionSendRequest {
        TransactionSendRequest {
            coin_type: None,
            tx: None,
            signatures: None,
        }
    }
}


