/*
 * OnChain Crypto Currency API
 *
 * Swagger definition for this API is available at https://io/docs/swagger.json
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionReply {
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "total_input_value", skip_serializing_if = "Option::is_none")]
    pub total_input_value: Option<i32>,
    #[serde(rename = "hashes_to_sign", skip_serializing_if = "Option::is_none")]
    pub hashes_to_sign: Option<Vec<crate::models::HashToSign>>,
}

impl TransactionReply {
    pub fn new() -> TransactionReply {
        TransactionReply {
            tx: None,
            total_input_value: None,
            hashes_to_sign: None,
        }
    }
}


