=begin
#OnChain Crypto Currency API

#We need to add a proper description.

OpenAPI spec version: 1.0
Contact: support@onchain.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13-SNAPSHOT

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/onchain_address_reply'
require 'swagger_client/models/onchain_balance_reply'
require 'swagger_client/models/onchain_balances_reply'
require 'swagger_client/models/onchain_coin_type'
require 'swagger_client/models/onchain_ethereum_transaction_reply'
require 'swagger_client/models/onchain_hash_to_sign'
require 'swagger_client/models/onchain_raw_transaction_send_request'
require 'swagger_client/models/onchain_transaction_reply'
require 'swagger_client/models/onchain_transaction_request'
require 'swagger_client/models/onchain_transaction_send_reply'
require 'swagger_client/models/onchain_transaction_send_request'

# APIs
require 'swagger_client/api/address_api'
require 'swagger_client/api/transaction_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
